//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAPI.Models.WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class contacto
    {
        public int idcontacto { get; set; }
        public string nombre { get; set; }
        public string celular { get; set; }
        public string direccion { get; set; }
        public string correo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public int idempresa { get; set; }
    
        public virtual empresa empresa { get; set; }
    }
}
